src/main/java/org/semux/gui/SwingUtil.java, src/main/java/org/semux/gui/dialog/InputDialog.java, src/main/java/org/semux/gui/panel/DelegatesPanel.java, src/main/java/org/semux/gui/panel/SendPanel.java
=> Implement editable text boxes

src/main/java/org/semux/CLI.java, src/main/java/org/semux/utils/SystemUtil.java
=> Implement password change feature on CLI

src/main/java/org/semux/GUI.java, src/main/java/org/semux/api/ApiHandlerImpl.java, src/main/java/org/semux/consensus/SemuxBFT.java, src/main/java/org/semux/consensus/SemuxSync.java, src/main/java/org/semux/core/Blockchain.java, src/main/java/org/semux/core/BlockchainImpl.java, src/main/java/org/semux/core/PendingManager.java, src/main/java/org/semux/gui/panel/DelegatesPanel.java, src/test/java/org/semux/api/APIHandlerTest.java, src/test/java/org/semux/core/CorePerfomanceTest.java, src/test/java/org/semux/core/TransactionExecutorTest.java, src/test/java/org/semux/core/state/DelegateStateTest.java
corrected the typo
Resolves #139
=> Correct the typo getDeleteState to getDelegateState

src/main/java/org/semux/gui/panel/DelegatesPanel.java
Fields get filled on PanelStart, delegates-click or account selection
change
another approach to #134
=> Fill in max possible Votes automatically

src/main/java/org/semux/gui/panel/HomePanel.java, src/main/resources/org/semux/gui/messages.properties
resolves #150
added the Sum of the total Balance + locked Balance to the HomePanel
=> Add Balance summed up to homePanel

src/main/java/org/semux/gui/panel/DelegatesPanel.java, src/main/resources/org/semux/gui/messages.properties
resolves #186
just gives a warning to the user
=> Check if balance is high enough to unvote

.github/issue_template.md
following the recommended community standard:
- https://github.com/semuxproject/semux/community
- https://help.github.com/articles/creating-an-issue-template-for-your-repository/
=> Add Github Issue Template

pom.xml, src/main/java/org/semux/cli/SemuxCLI.java, src/main/java/org/semux/crypto/EdDSA.java, src/test/java/org/semux/cli/SemuxCLITest.java, src/test/java/org/semux/crypto/EdDSATest.java
=> CLI: add importprivatekey

.github/code_of_conduct.md, .github/contributing.md, .github/issue_template.md, README.md
In progress
https://github.com/semuxproject/semux/community
=> Update community profile

src/main/java/org/semux/core/BlockchainImpl.java, src/main/java/org/semux/db/DBDump.java, src/test/java/org/semux/core/BlockchainImplTest.java
=> Clean up database schema

src/main/java/org/semux/gui/Action.java, src/main/java/org/semux/gui/MenuBar.java, src/main/java/org/semux/gui/dialog/PrivateKeyDumpDialog.java, src/main/resources/org/semux/gui/messages.properties
resolves #238
cleaned up the mess
=> GUI Add export private key feature

.travis.yml, .travis/start_xvfb.sh, pom.xml, src/main/java/org/semux/core/state/Delegate.java, src/main/java/org/semux/gui/panel/DelegatesPanel.java, src/main/resources/org/semux/gui/messages.properties, src/test/java/org/semux/gui/BaseTestApplication.java, src/test/java/org/semux/gui/panel/DelegatePanelTest.java, src/test/java/org/semux/gui/panel/DelegatePanelTestApplication.java
=> Display Selected Delegate on DelegatePanel

.scrutinizer.yml, README.md
In addition to the existing code style checking in CI process, static code analysis can help the project to prevent low-quality code from being introduced. [Scrutinizer CI](https://scrutinizer-ci.com/) provides multiple measurement metrics based on tools like [SonarLint](https://www.sonarlint.org/) and [PMD](https://pmd.github.io/) can help contributors to discover potential issues in their pull requests.
The configuration of scrutinizer.yml rejects pull requests which:
- introduce new classes/methods with a rating of B or worse
- introduce new issues of MAJOR or higher severity
- bring down Code Quality Rating below 9 (current rating is 9.5)
https://scrutinizer-ci.com/g/cryptokat/semux/issues
=> Add Scrutinizer CI Integration

pom.xml, src/main/java/org/semux/cli/SemuxCLI.java, src/main/java/org/semux/gui/SemuxGUI.java, src/main/java/org/semux/log/LoggerConfigurator.java, src/main/java/org/semux/wrapper/Wrapper.java, src/test/java/org/semux/log/LoggerConfiguratorTest.java
resolves #274 
Users will be able to customize loggers by modifying `config/logback.xml` following logback documentation.
- #279 
- log rotation: https://logback.qos.ch/manual/appenders.html#RollingFileAppender
- log filtering: https://logback.qos.ch/manual/filters.html
=> Logback Customization

appveyor.yml
hopefully we will be able to catch some bugs for 32bit windows users
=> Enable 32bit JVM testing on appveyor

src/main/java/org/semux/Kernel.java, src/main/java/org/semux/core/Unit.java, src/main/java/org/semux/exception/KernelException.java, src/main/java/org/semux/gui/SemuxGUI.java, src/main/java/org/semux/gui/SwingUtil.java, src/main/java/org/semux/gui/exception/QRCodeException.java, src/main/java/org/semux/gui/panel/ReceivePanel.java, src/main/resources/org/semux/gui/messages.properties
https://scrutinizer-ci.com/g/semuxproject/semux/inspections/4c46037e-f654-4def-a9db-f054c1b99994/issues/?status=fixed
- Config.java: https://scrutinizer-ci.com/g/semuxproject/semux/issues/develop/files/src/main/java/org/semux/Config.java?selectedSeverities%5B0%5D=10&orderField=path&order=asc&honorSelectedPaths=0
- Constructor has 8 parameters, which is greater than 7 authorized.
- https://scrutinizer-ci.com/g/semuxproject/semux/issues/develop/files/src/main/java/org/semux/core/BlockHeader.java?selectedSeverities%5B0%5D=10&orderField=path&order=asc&honorSelectedPaths=0
- https://scrutinizer-ci.com/g/semuxproject/semux/issues/develop/files/src/main/java/org/semux/core/Genesis.java?selectedSeverities%5B0%5D=10&orderField=path&order=asc&honorSelectedPaths=0
Regarding the second point of "too …
=> Fix More Reported Issues From Scrutinizer 

src/test/java/org/semux/log/LoggerConfiguratorTest.java
=> Tests: resolves #297

src/main/java/org/semux/gui/panel/HomePanel.java
resolves #311 
refactoring due to sonarlint hints
=> GUI adjust TX Panel in HomePanel

src/main/java/org/semux/api/ApiHandler.java, src/main/java/org/semux/api/ApiHandlerImpl.java, src/main/java/org/semux/api/HttpHandler.java, src/main/java/org/semux/api/response/ApiHandlerResponse.java, src/main/java/org/semux/api/response/GetBlockResponse.java, src/main/java/org/semux/api/transaction/TransactionBuilder.java, src/main/java/org/semux/crypto/Hex.java, src/test/java/org/semux/api/ApiHandlerErrorTest.java, src/test/java/org/semux/api/ApiHandlerTest.java, src/test/java/org/semux/api/ApiHandlerTestBase.java, src/test/java/org/semux/api/ApiServerRule.java, src/test/java/org/semux/api/HttpHandlerTest.java, src/test/java/org/semux/api/transaction/TransactionBuilderTest.java, src/test/java/org/semux/crypto/HexTest.java
The pull request improves error handling and test coverage of API server.
=> Improve API Error Handling

Dockerfile
dockerfile is broken by the renamed tarball
=> Tools: update dockerfile

src/main/java/org/semux/consensus/SemuxSync.java, src/main/java/org/semux/core/SyncManager.java, src/main/java/org/semux/gui/SemuxGUI.java, src/main/java/org/semux/gui/model/WalletModel.java, src/main/java/org/semux/gui/panel/HomePanel.java, src/main/resources/org/semux/gui/messages.properties, src/test/java/org/semux/gui/panel/HomePanelTest.java, src/test/java/org/semux/gui/panel/HomePanelTestApplication.java
=> Add GUI Sync Progress

src/main/java/org/semux/api/ApiHandlerImpl.java, src/main/java/org/semux/consensus/SemuxBFT.java, src/main/java/org/semux/core/PendingManager.java, src/main/java/org/semux/gui/panel/DelegatesPanel.java, src/main/java/org/semux/gui/panel/SendPanel.java, src/main/resources/org/semux/gui/messages.properties, src/test/java/org/semux/api/ApiHandlerTest.java, src/test/java/org/semux/core/PendingManagerTest.java, src/test/java/org/semux/gui/WalletRule.java, src/test/java/org/semux/gui/panel/DelegatePanelTest.java, src/test/java/org/semux/gui/panel/DelegatePanelTestApplication.java, src/test/java/org/semux/gui/panel/SendPanelTest.java
To make it less confusing for users when a transaction is rejected
=> Report Cause of Rejection From PendingManager

src/main/java/org/semux/gui/SwingUtil.java, src/test/java/org/semux/gui/SwingUtilTest.java
=> GUI: consider empty parameter of SwingUtil.parseNumber

pom.xml
see https://github.com/gary-rowe/BitcoinjEnforcerRules
=> Tools: add BitcoinjEnforcerRules to avoid dependency-chain attack

src/main/java/org/semux/gui/panel/SendPanel.java, src/test/java/org/semux/gui/panel/SendPanelTest.java
=> GUI: consider invalid address in SendPanel

src/main/java/org/semux/cli/SemuxCLI.java, src/main/resources/org/semux/cli/messages.properties, src/test/java/org/semux/cli/SemuxCLITest.java
=> Confirm New Password in CLI

src/main/java/org/semux/gui/dialog/AddAddressDialog.java
=> Fix Localization of Add Address

src/main/java/org/semux/core/BlockchainImpl.java, src/test/java/org/semux/core/BlockchainImplTest.java
=> Core: prevent a self-transaction from being added into index db twice

src/main/java/org/semux/consensus/SemuxBFT.java, src/test/java/org/semux/consensus/SemuxBFTOnNewHeightTest.java, src/test/java/org/semux/consensus/SemuxBFTTest.java
=> Tests: add SemuxBFTOnNewHeightTest

src/main/java/org/semux/gui/Action.java, src/main/java/org/semux/gui/MenuBar.java
=> GUI: Add help menu item to launch wiki

appveyor.yml, pom.xml, scripts/release.sh, src/main/java/org/semux/config/AbstractConfig.java
This will make it more clear for developers where to address issues reported from end-users
=> Tools: append commit hash to version number

config/semux.properties, src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/config/Config.java, src/main/java/org/semux/config/DevNetConfig.java, src/main/java/org/semux/net/Channel.java, src/main/java/org/semux/net/ConnectionLimitHandler.java, src/main/java/org/semux/net/PeerServer.java, src/test/java/org/semux/gui/SemuxGUITest.java, src/test/java/org/semux/integration/ConnectionTest.java, src/test/java/org/semux/net/ConnectionLimitHandlerTest.java
reopening #423 
Index of `connectionCount` has been switched from `InetAddress` to `String`
=> Limit Inbound Connections of Each Unique IP Address

src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/config/Config.java, src/main/java/org/semux/consensus/SemuxBFT.java, src/main/java/org/semux/core/PendingManager.java, src/test/java/org/semux/consensus/SemuxBFTValidateBlockTest.java
A malicious validator may propose a block with a timestamp in the future which suspend the network indefinitely
=> Consensus: reject a block in the future

src/main/resources/org/semux/gui/messages.properties
'Confirm to delete account' yes/no reads strangely.
Other dialogs ask the user as a question.
=> GUI: Wording for confirm delete dialog

src/main/java/org/semux/net/ConnectionLimitHandler.java, src/test/java/org/semux/integration/ConnectionTest.java, src/test/java/org/semux/net/ConnectionLimitHandlerTest.java
remove a mapping when the counter becomes 0
=> Net: fix memory-leak of ConnectionLimitHandler

config/semux.properties, src/main/java/org/semux/cli/SemuxCLI.java, src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/config/Config.java, src/main/java/org/semux/gui/SemuxGUI.java, src/main/java/org/semux/util/SystemUtil.java
Enable users to specify the localization of UI in `semux.properties`
=> Config: add ui.locale

scripts/release.sh
=> Tools: generate sha1 checksum of archive in release.sh

src/main/java/org/semux/Kernel.java, src/main/java/org/semux/consensus/Proposal.java, src/main/java/org/semux/core/TransactionResult.java, src/main/java/org/semux/gui/MenuBar.java, src/main/java/org/semux/gui/SemuxGUI.java, src/main/java/org/semux/gui/SwingUtil.java
=> Trivial: Fix typos

LICENSE_3RD, pom.xml, src/main/java/org/semux/api/SemuxApi.java, src/main/java/org/semux/api/SemuxApiImpl.java
Swagger can be used for client generation
and documentation generation.
fixes #324
=> API: Add swagger API annotations

src/main/java/org/semux/gui/panel/TransactionsPanel.java, src/main/resources/org/semux/gui/messages.properties, src/test/java/org/semux/gui/panel/TransactionsPanelTest.java, src/test/java/org/semux/rules/KernelRule.java
Since there is a 30 second delay, it would be
beneficial to show pending transactions to users
fixes #335
=> [wip] GUI: Show pending transactions

src/main/java/org/semux/gui/dialog/AddAddressDialog.java, src/main/resources/org/semux/gui/messages.properties
=> Validate Address on add to addressbook

src/main/java/org/semux/gui/MainFrame.java, src/main/java/org/semux/gui/SemuxGui.java
=> GUI: Ensure all frames are destroyed before the application starts closing the kernel

src/main/java/org/semux/gui/panel/DelegatesPanel.java, src/main/resources/org/semux/gui/messages.properties, src/test/java/org/semux/gui/panel/DelegatePanelTest.java
Add tests and validation for attempting to unvote with no votes
for that delegate.
fixes #497
=> GUI: Add validation for unvoting with no votes

src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/api/response/Types.java, src/test/java/org/semux/api/ApiHandlerTest.java
=> API: add data field TransactionType#blockNumber

src/main/java/org/semux/core/BlockchainImpl.java, src/test/java/org/semux/core/BlockchainImplTest.java
handle a special case for coinbase transactions
=> Core: fix BlockchainImpl#getTransactionBlockNumber

src/test/java/org/semux/cli/SemuxCliTest.java, src/test/java/org/semux/integration/ConnectionTest.java, src/test/java/org/semux/integration/SyncingTest.java, src/test/java/org/semux/integration/TransactTest.java, src/test/java/org/semux/log/LoggerConfiguratorTest.java, src/test/java/org/semux/wrapper/WrapperTest.java, src/test/resources/org/powermock/extensions/configuration.properties
see https://stackoverflow.com/questions/41603303/powermockignore-at-project-level
=> Tests: fix #529

src/main/java/org/semux/Launcher.java, src/main/java/org/semux/cli/SemuxCli.java, src/main/java/org/semux/exception/LauncherException.java, src/main/java/org/semux/gui/SemuxGui.java, src/main/java/org/semux/util/SystemUtil.java, src/test/java/org/semux/util/SystemUtilTest.java
To resolve #521. The check is implemented using Windows registry reader provided by JNA.
Tested under:
=> Detect Installation of Microsoft Visual C++ 2010 Redistributable Package Under Windows Platform

src/main/java/org/semux/gui/SwingUtil.java
=> GUI: focus text field on right click

src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/api/response/Types.java, src/test/java/org/semux/api/ApiHandlerTest.java, src/test/java/org/semux/api/ApiHandlerTestBase.java
=> API: add a data field `transactionCount` to the response of `/get_account` API

src/main/java/org/semux/api/http/HttpHandler.java
Pretty print is easier for human legibility
And does not add much extra payload size
=> API: Pretty print response

src/main/java/org/semux/gui/MenuBar.java
Update to show icon and change title to match
what is being displayed.
More could probably be done here to display
copyright and website and other normal information
found in an about dialog, but it's a start.
=> GUI: Update about dialog.

src/main/java/org/semux/gui/MenuBar.java
The export private key dialog has a title,
update import to match for consistency.
=> GUI: Import dialog has title

src/main/java/org/semux/gui/panel/ReceivePanel.java
Found another location where adding a
dialog title would be informative as to
what is being asked.
=> GUI: Rename account has title

src/main/java/org/semux/api/SemuxApiImpl.java
Was told TravisCI doesn't like this file, so
I re-ran formatting.  Hope this helps
=> Trivial: fix formatting of javadoc

src/main/java/org/semux/gui/MainFrame.java, src/main/java/org/semux/gui/MenuBar.java
GUI, Trivial introduce some mnemonic keys to the Wallet UI:
Alt+
- Home: H
- Send: S
- Receive: R
- Transactions: T
- Delegates: D
- Lock: L
resolves #489
=> GUI: Add Mnemonic Keys to the UI

src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/core/Wallet.java, src/main/java/org/semux/gui/MenuBar.java, src/main/java/org/semux/gui/WelcomeFrame.java, src/test/java/org/semux/core/WalletTest.java
Import the new wallets address book.
Chose to not override any existing aliases, but could
go either way on that one.  There is little chance of overlap.
Prefer to keep existing wallet as source of truth if conflicts arise
fixes #565
=> GUI: Import wallet imports addressbook too

src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/gui/dialog/AddressBookDialog.java, src/main/java/org/semux/gui/dialog/AddressBookEntryChangeDialog.java, src/main/resources/org/semux/gui/messages.properties
Added a dialog to the address book for
changing adress book entries
resolves #482
=> GUI: add address book edit dialog

src/main/java/org/semux/api/SemuxApi.java
=> API: Add parameter descriptions

src/main/java/org/semux/core/Wallet.java
Resolve TODOs around wallet lookups.
Use LinkedHashMap to maintain order.
We're using a synchronized collection
yet usages look to all be protected with
synchronized.  It might be better to not use
synchronized wrapper, after double checking
synchronization.
Would like to discuss, and possibly add another
test before merging.
=> Core: Wallet lookups do not iterate list

src/main/java/org/semux/gui/MainFrame.java, src/main/java/org/semux/gui/dialog/AddressBookDialog.java, src/main/java/org/semux/gui/model/WalletModel.java
address book dialog will be disposed instead of locked
resolves #595
=> GUI: Lock addressbook

src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/api/response/SignMessageResponse.java, src/main/java/org/semux/api/response/VerifyMessageResponse.java, src/main/java/org/semux/core/PendingManager.java, src/main/java/org/semux/core/Wallet.java, src/main/java/org/semux/gui/MenuBar.java, src/main/java/org/semux/gui/WelcomeFrame.java, src/test/java/org/semux/api/ApiHandlerTest.java, src/test/java/org/semux/net/msg/p2p/HelloMessageTest.java, src/test/java/org/semux/net/msg/p2p/WorldMessageTest.java
=> API: do not look up transaction block number for /get_pending_transactions

src/main/java/org/semux/gui/Action.java, src/main/java/org/semux/gui/SemuxGui.java, src/main/java/org/semux/gui/panel/ReceivePanel.java, src/main/java/org/semux/gui/panel/SendPanel.java, src/test/java/org/semux/gui/panel/ReceivePanelTest.java
=> GUI: delegate the account renaming to address book

src/main/java/org/semux/api/SemuxApiImpl.java
Add validation inline with other parameters
=> API: Validate hash on getBlock calls

src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/api/util/TransactionBuilder.java
Add missing validations and make sure validation
message formats are consistent.
=> API: Update messages to be consistent

.travis.yml, README.md, appveyor.yml, pom.xml, src/main/java/org/semux/gui/MainFrame.java, src/main/java/org/semux/gui/SemuxGui.java, src/main/java/org/semux/gui/TextPrompt.java, src/main/java/org/semux/gui/dialog/AddressBookDialog.java, src/main/java/org/semux/gui/dialog/AddressBookUpdateDialog.java, src/main/java/org/semux/gui/model/WalletAccount.java, src/main/java/org/semux/gui/panel/DelegatesPanel.java, src/main/java/org/semux/gui/panel/SendPanel.java, src/main/java/org/semux/log/LoggerConfigurator.java, src/main/java/org/semux/net/ConnectionLimitHandler.java, src/main/java/org/semux/util/SystemUtil.java, src/test/java/org/semux/cli/SemuxCliTest.java, src/test/java/org/semux/consensus/SemuxBftValidateBlockTest.java, src/test/java/org/semux/gui/WalletModelRule.java, src/test/java/org/semux/gui/model/WalletAccountTest.java, src/test/java/org/semux/gui/panel/ReceivePanelTest.java, src/test/java/org/semux/gui/panel/TransactionsPanelTest.java, src/test/java/org/semux/integration/ConnectionTest.java, src/test/java/org/semux/integration/SyncingTest.java, src/test/java/org/semux/integration/TransactTest.java, src/test/java/org/semux/log/LoggerConfiguratorTest.java, src/test/java/org/semux/wrapper/WrapperTest.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, src/test/resources/org/powermock/extensions/configuration.properties
Add support for Java SE 9, with the min required Java SE 8
See also: #637 #639  #641
=> Add Java 9 Support 

src/main/java/org/semux/consensus/SemuxBft.java
=> Consensus: don't sync when in FINALIZE state

src/main/java/org/semux/gui/dialog/TransactionDialog.java
=> GUI: enable line wrapping and scroll bar on data fields

src/main/java/org/semux/net/NodeManager.java
fix https://github.com/semuxproject/semux/pull/662/files#r167449456
=> Net: trim dns seed name

pom.xml, src/main/java/org/semux/util/SystemUtil.java, src/main/java/org/semux/wrapper/Wrapper.java, src/test/java/org/semux/util/SystemUtilTest.java, src/test/java/org/semux/wrapper/WrapperTest.java
=> Wrapper: mark nio modules as accessible for Java9 Netty

pom.xml, src/main/java/org/semux/util/SystemUtil.java, src/test/java/org/semux/gui/dialog/ConsoleDialogTest.java
This implementation stores commit version in an independent resource file.
=> Util: fix SystemUtil#getImplementationVersion for Java 9 using an alternative implementation

src/main/java/org/semux/gui/dialog/ConsoleDialog.java
Scrolling to the bottom of the output after each command
should feel more natural to user.
=> GUI: Scroll to bottom of console after command

.travis.yml, README.md, pom.xml, src/main/java/org/semux/config/exception/ConfigException.java, src/main/java/org/semux/util/SystemUtil.java
=> Docs: change recommended java version

config/semux.properties, src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/config/Config.java, src/main/java/org/semux/core/Unit.java, src/main/java/org/semux/gui/SemuxGui.java, src/main/java/org/semux/gui/SwingUtil.java, src/main/java/org/semux/gui/panel/HomePanel.java, src/main/java/org/semux/gui/panel/SendPanel.java, src/test/java/org/semux/gui/SwingUtilTest.java
=> Support Customized Base Unit

src/main/java/org/semux/cli/SemuxCli.java, src/main/java/org/semux/gui/SemuxGui.java, src/main/java/org/semux/net/filter/FilterRule.java, src/main/java/org/semux/net/filter/SemuxIpFilter.java, src/main/java/org/semux/net/filter/exception/IpFilterJsonParseException.java, src/test/java/org/semux/net/filter/SemuxIpFilterLoaderTest.java
=> GUI,CLI: improve error reporting of ipfilter.json parsing

.github/contributing.md, .scrutinizer.yml, .travis.yml, README.md, pom.xml, src/main/java/org/semux/Kernel.java, src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/cli/SemuxCli.java, src/main/java/org/semux/gui/MainFrame.java, src/main/java/org/semux/gui/SemuxGui.java, src/main/java/org/semux/gui/dialog/AddressBookDialog.java, src/main/java/org/semux/gui/panel/ReceivePanel.java, src/main/java/org/semux/gui/panel/TransactionsPanel.java, src/main/java/org/semux/util/IOUtil.java, src/main/java/org/semux/util/SystemUtil.java, src/test/java/org/semux/util/IOUtilTest.java
=> Replace Scrutinizer-CI With FindBugs Maven Plugin

src/main/java/org/semux/Launcher.java, src/main/java/org/semux/core/PendingManager.java, src/main/java/org/semux/util/SystemUtil.java, src/test/java/org/semux/util/SystemUtilTest.java
update method for 2012 as that's what we check.
Also change method to return 0 hardcoded to match the if
statement above for consistency.
=> Trivial: rename method

pom.xml, src/main/java/org/semux/core/BlockchainImpl.java, src/test/java/org/semux/core/BlockchainImplTest.java
=> Optimize BlockchainImpl#forkActivated by returning memoized result of current height

src/main/java/org/semux/Kernel.java, src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/config/Config.java
=> DB: separate database from different network

CHANGELOG.md
=> Docs: add v1.1.0 changelog

pom.xml, src/main/java/org/semux/cli/SemuxCli.java, src/main/java/org/semux/core/Wallet.java, src/main/java/org/semux/gui/SemuxGui.java, src/main/java/org/semux/util/SystemUtil.java, src/main/resources/org/semux/cli/messages.properties, src/main/resources/org/semux/gui/messages.properties, src/test/java/org/semux/cli/SemuxCliTest.java, src/test/java/org/semux/core/WalletTest.java, src/test/java/org/semux/gui/SemuxGuiTest.java, src/test/java/org/semux/util/SystemUtilTest.java
=> Tools: secure access permission of dist config files

src/main/java/org/semux/util/SystemUtil.java
=> Util: cache client version

src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/db/LeveldbDatabase.java, src/main/java/org/semux/util/SystemUtil.java, src/test/java/org/semux/config/MainnetConfigTest.java
fix #811
see: https://dzone.com/articles/policemans-horror-default
=> Util: make String#toLowerCase become locale insensitive

src/main/java/org/semux/gui/SplashScreen.java, src/main/java/org/semux/gui/StatusBar.java, src/main/java/org/semux/gui/SwingUtil.java, src/test/java/org/semux/gui/SplashScreenTest.java
=> GUI: improve splash screen & status bar

src/main/java/org/semux/core/Wallet.java
extra call for key, and fix private
=> Wallet: remove extraneous call

src/main/java/org/semux/gui/TextPrompt.java
just some typos and some variables that can be scoped final
=> Trivial: typos in prompt class

src/main/java/org/semux/api/v2_0_0/impl/SemuxApiServiceImpl.java, src/main/resources/org/semux/api/v2_0_0/swagger.json, src/test/java/org/semux/TestUtils.java, src/test/java/org/semux/api/v2_0_0/SemuxApiErrorTest.java, src/test/java/org/semux/api/v2_0_0/SemuxApiTest.java, src/test/java/org/semux/api/v2_0_0/SemuxApiTestBase.java
=> API: validate transactions in POST /transaction/raw

src/main/java/org/semux/api/v2_0_0/TypeFactory.java, src/main/java/org/semux/api/v2_0_0/impl/SemuxApiServiceImpl.java, src/main/resources/org/semux/api/v2_0_0/swagger.json, src/test/java/org/semux/TestUtils.java, src/test/java/org/semux/api/v2_0_0/SemuxApiTest.java
=> API: add 'GET /account/pending-transactions?address&from&to'

src/main/java/org/semux/api/v2_0_0/TypeFactory.java, src/main/java/org/semux/api/v2_0_0/impl/SemuxApiServiceImpl.java, src/main/resources/org/semux/api/v2_0_0/swagger.json, src/test/java/org/semux/api/v2_0_0/SemuxApiTest.java
=> API: DelegateType has "validator" flag

docs/Full-Node-Setup.md, docs/README.md, misc/systemd/semux.service
=> Docs: add full node setup guide

docs/RESTful-API.md
API examples for #842 will be added in each client respectively
=> Docs: link to API clients

CHANGELOG.md, pom.xml, src/main/java/org/semux/config/Constants.java
=> Bump Version to 1.2.0

src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/config/Config.java, src/main/java/org/semux/config/Constants.java, src/main/java/org/semux/config/DevnetConfig.java, src/main/java/org/semux/config/MainnetConfig.java, src/main/java/org/semux/config/TestnetConfig.java, src/main/java/org/semux/consensus/SemuxBft.java, src/main/java/org/semux/consensus/SemuxSync.java, src/main/java/org/semux/core/Block.java, src/main/java/org/semux/core/BlockchainImpl.java, src/main/java/org/semux/core/PendingManager.java, src/main/java/org/semux/core/Transaction.java, src/main/java/org/semux/core/TransactionResult.java, src/main/java/org/semux/net/SemuxChannelInitializer.java, src/test/java/org/semux/api/v2_0_0/SemuxApiTest.java, src/test/java/org/semux/consensus/SemuxSyncTest.java, src/test/java/org/semux/core/PendingManagerTest.java
=> A Few Consensus Cleanups

src/main/java/org/semux/consensus/Vote.java, src/main/java/org/semux/net/ConnectionLimitHandler.java, src/test/java/org/semux/net/ConnectionLimitHandlerTest.java
=> Fix memory leak issue

src/main/java/org/semux/gui/HorizontalSeparator.java, src/main/java/org/semux/gui/MainFrame.java, src/main/java/org/semux/gui/SemuxGui.java, src/main/java/org/semux/gui/StatusBar.java, src/main/java/org/semux/gui/VerticalSeparator.java, src/main/java/org/semux/gui/model/WalletModel.java, src/main/java/org/semux/gui/panel/HomePanel.java, src/main/resources/org/semux/gui/messages.properties, src/test/java/org/semux/gui/MainFrameTest.java, src/test/java/org/semux/gui/SemuxGuiTest.java, src/test/java/org/semux/gui/model/WalletModelTest.java, src/test/java/org/semux/gui/panel/HomePanelTest.java, src/test/java/org/semux/gui/panel/HomePanelTestApplication.java
=> GUI: Add Consensus Info Table

README.md
[![Throughput Graph](https://graphs.waffle.io/semuxproject/semux/throughput.svg)](https://waffle.io/semuxproject/semux/metrics/throughput)
=> Docs: add a throughput chart to demonstrate the hard work of developers

src/main/java/org/semux/gui/dialog/SelectDialog.java, src/main/java/org/semux/gui/panel/DelegatesPanel.java
=> GUI: Long aliases should not break rendering

docs/Block-Explorers.md, docs/Block-Rewards.md, docs/Bug-Bounty-Program.md, docs/Delegate-Pools.md, docs/README.md, docs/RESTful-API.md, docs/Semux-BFT-Consensus.md, docs/Testnet.md
Reorganize docs a little.  Add some consistent headers
and descriptions of what a page is to contain.
=> Docs: Update docs boilerplate

src/main/java/org/semux/api/v2_1_0/impl/SemuxApiServiceImpl.java, src/main/resources/org/semux/api/v2_1_0/swagger.json, src/test/java/org/semux/api/v2_1_0/SemuxApiTest.java
The endpoint was mistakenly removed in #872
=> API: re-add 'GET /syncing' endpoint introduced by #868

src/main/java/org/semux/gui/dialog/SelectDialog.java
Inadvertantly broke dropdown.
fixes #882
=> GUI: Fix select dropdown

src/main/java/org/semux/cli/SemuxCli.java
=> CLI: don't dump private key on import

src/test/java/org/semux/cli/SemuxCliTest.java
=> Tests: fix testImportPrivateKey

src/main/java/org/semux/gui/dialog/SelectDialog.java
=> GUI: fix an issue that there is no task bar icon for coinbase selection dialog under windows

src/main/java/org/semux/gui/panel/SendPanel.java
Avoid logspam with attempting to read from wallet for rending address
book.
fixes #907
=> GUI: check if wallet unlocked before updating send

src/main/java/org/semux/gui/panel/SendPanel.java
=> GUI: Account ordering is consistent across panels
