src/main/java/org/semux/gui/WelcomeFrame.java
removed the password repeat textfield and validation 
when restoring the wallet from a backed up file
=> Remove passwort repeat textfield on restore from backup

src/main/java/org/semux/gui/SwingUtil.java, src/main/java/org/semux/gui/dialog/TransactionDialog.java, src/main/java/org/semux/gui/panel/DelegatesPanel.java, src/main/java/org/semux/gui/panel/HomePanel.java, src/main/java/org/semux/gui/panel/ReceivePanel.java, src/main/java/org/semux/gui/panel/SendPanel.java, src/main/java/org/semux/gui/panel/TransactionsPanel.java, src/test/java/org/semux/gui/SwingUtilTest.java
Localized double values use different decimal seperators. 
Double.parse(str) can't handle this.
Fixed it with using NumberFormat.parse(str).doubleValue()
=> Fix NumberFormatExceptions on parsing doubles from inputFields

appveyor.yml, pom.xml, src/test/java/org/semux/IntegrationTest.java, src/test/java/org/semux/windows/Launch4jWrapperIT.java, src/test/java/org/semux/windows/WindowsIntegrationTest.java
To resolve #228 
The pull request adds a windows-specific integration test for checking whether the created Launch4j wrapper can be successfully executed.
=> Tests: add launch4j integration test

pom.xml, src/main/java/org/semux/consensus/SemuxSync.java, src/main/java/org/semux/crypto/EdDSA.java, src/main/java/org/semux/crypto/cache/EdDSAPublicKeyCache.java, src/main/java/org/semux/util/TimeUtil.java, src/test/java/org/semux/bench/CorePerformance.java, src/test/java/org/semux/bench/CryptoLargePerformance.java, src/test/java/org/semux/bench/CryptoPerformance.java, src/test/java/org/semux/util/TimeUtilTest.java
According to profiling results, EdDSAPublicKey constructor consumes ~37% of CPU time of `EdDSAPublicKey::verify` mainly by [creating precomputed tables](https://github.com/str4d/ed25519-java/blob/master/src/net/i2p/crypto/eddsa/spec/EdDSAPublicKeySpec.java#L39). Considering that Semux has an infrequently changed list of validators, caching public keys can reduce the synchronization time significantly.
The benchmark was running against the mainnet at the height of ~15K
~42% saved CPU time on sync thread
=> Increase Synchronization Performance by Caching EdDSAPublicKey

src/main/java/org/semux/api/HttpChannelInitializer.java, src/main/java/org/semux/api/SemuxAPI.java, src/test/java/org/semux/api/HttpHandlerTest.java, src/test/java/org/semux/log/LoggerConfiguratorTest.java
[A recent change](https://github.com/semuxproject/semux/commit/536469294e302f7a6b9b6c48b196c986615a5b80#diff-185beb24e446140927fa652e90b14e57L66) introduced an issue that SemuxAPI server is reusing a single instance of HttpHandler for all requests causing the following exception:
```
2017-12-04 15:43:42 [api-2] WARN  ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x267cbe48, L:/127.0.0.1:5171 - R:/127.0.0.1:53482]
io.netty.channel.ChannelPipelineException: org.semux.api.HttpHandler is not a @Sharable handler, so can't be added or removed multiple times.
at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:588)
at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:199)
at …
```
=> API: do not reuse http handler instance

src/main/java/org/semux/util/SystemUtil.java, src/test/java/org/semux/util/SystemUtilTest.java
Retrieve public IP by looking up `myip.opendns.com` on [opendns](https://en.wikipedia.org/wiki/OpenDNS) enables network redundancy of SystemUtil::getIp and reduces the chance of issues like #336
=> Util: replace ipify with opendns

.travis.yml, .travis/start_xvfb.sh, pom.xml, src/main/java/org/semux/gui/panel/ReceivePanel.java, src/test/java/org/semux/gui/panel/DelegatePanelTest.java, src/test/java/org/semux/gui/panel/HomePanelTest.java, src/test/java/org/semux/gui/panel/ReceivePanelTest.java, src/test/java/org/semux/gui/panel/SendPanelTest.java
For some reason GUI tests are failing randomly on Travis-CI. Enabling `rerunFailingTestsCount` of surefire plugin can help us get rid of failing builds for now.
Flaky tests will be reported as the following image:
=> Allow Flaky Tests

src/main/java/org/semux/util/MerkleTree.java, src/test/java/org/semux/util/MerkleTreeTest.java
CVE-2012-2459 has been addressed by BIP 98
- https://github.com/bitcoin/bips/blob/master/bip-0098.mediawiki#fast-merkle-lists
=> Util: fix cve-2012-2459 (breaking change)

src/main/java/org/semux/consensus/SemuxBFT.java, src/main/java/org/semux/consensus/SemuxSync.java, src/main/java/org/semux/core/Blockchain.java, src/main/java/org/semux/core/BlockchainImpl.java, src/main/java/org/semux/core/PendingManager.java, src/main/java/org/semux/core/TransactionResult.java, src/test/java/org/semux/consensus/SemuxBFTTest.java, src/test/java/org/semux/consensus/SemuxSyncTest.java, src/test/java/org/semux/core/BlockchainImplTest.java, src/test/java/org/semux/core/PendingManagerTest.java, src/test/java/org/semux/rules/KernelRule.java
Currently it's possible that an existing transaction gets overwritten in local blockchain database. The issue can be addressed by rejecting all existing transactions by looking up the `indexDb`.
- https://github.com/bitcoin/bips/blob/master/bip-0030.mediawiki
- https://github.com/bitcoin/bitcoin/commit/a206b0ea12eb4606b93323268fc81a4f1f952531
=> Reject Transactions With Duplicated Hash

src/main/java/org/semux/api/ApiHandlerImpl.java, src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/config/Config.java, src/main/java/org/semux/net/NodeManager.java, src/main/java/org/semux/net/SemuxP2pHandler.java, src/main/java/org/semux/net/msg/p2p/NodesMessage.java, src/test/java/org/semux/integration/TransferTest.java, src/test/java/org/semux/net/NodeManagerTest.java, src/test/java/org/semux/net/msg/p2p/NodesMessageTest.java
`NodeManager` may be vulnerable to OOM DoS when a malicious peer sends a large number of nodes through `NodesMessage`
=> Limit number of nodes in NodesMessage 

src/main/java/org/semux/gui/SwingUtil.java, src/main/java/org/semux/gui/TextContextMenuItem.java, src/main/java/org/semux/gui/dialog/AddAddressDialog.java, src/main/java/org/semux/gui/dialog/AddressBookDialog.java, src/main/java/org/semux/gui/dialog/DelegateDialog.java, src/main/java/org/semux/gui/dialog/ExportPrivateKeyDialog.java, src/main/java/org/semux/gui/dialog/TransactionDialog.java, src/test/java/org/semux/gui/dialog/AddressBookDialogTest.java, src/test/java/org/semux/gui/dialog/AddressBookDialogTestApplication.java, src/test/java/org/semux/gui/dialog/DelegateDialogTest.java, src/test/java/org/semux/gui/dialog/DelegateDialogTestApplication.java, src/test/java/org/semux/gui/dialog/TransactionDialogTest.java, src/test/java/org/semux/gui/dialog/TransactionDialogTestApplication.java
Close button of dialogs is not currently displayed in GNOME desktop.
=> Fix Close Button of Dialogs in GNOME and Other Trivial GUI Issues

src/main/java/org/semux/consensus/SemuxBFT.java, src/main/java/org/semux/consensus/SemuxSync.java, src/main/java/org/semux/core/Blockchain.java, src/main/java/org/semux/core/BlockchainImpl.java, src/test/java/org/semux/consensus/SemuxBFTTest.java, src/test/java/org/semux/core/BlockchainImplTest.java, src/test/java/org/semux/integration/TransactionTest.java, src/test/java/org/semux/rules/KernelRule.java
`SemuxSync` may be vulnerable to OOM DoS when `SemuxBFT` receives a `BFT_NEW_HEIGHT` message with a large `height` property.
=> Avoid OOM caused by malicious BFT_NEW_HEIGHT messages

src/main/java/org/semux/api/ApiHandlerImpl.java, src/main/java/org/semux/api/Command.java, src/main/java/org/semux/api/response/GetTransactionLimitsResponse.java, src/test/java/org/semux/api/ApiHandlerErrorTest.java, src/test/java/org/semux/api/ApiHandlerTest.java
A general purpose API `/get_transaction_limits?type` to retrieve limitations on making a type of transaction is proposed in this pull request for #445
=> API: add /get_transaction_limits?type

src/main/java/org/semux/api/ApiHandlerResponse.java, src/main/java/org/semux/api/HttpHandler.java
It's an anti pattern to have objects serialize
themselves.  Best practice is to reuse the
object mapper.  This allows for customization
down the road (pretty print, etc)
=> API: Reuse object mapper

src/main/java/org/semux/api/response/Types.java, src/main/java/org/semux/net/Capability.java, src/main/java/org/semux/net/CapabilitySet.java, src/main/java/org/semux/net/Peer.java, src/main/java/org/semux/net/SemuxP2pHandler.java, src/test/java/org/semux/api/ApiHandlerTest.java, src/test/java/org/semux/net/CapabilityTest.java, src/test/java/org/semux/net/PeerTest.java, src/test/java/org/semux/net/msg/p2p/HelloMessageTest.java, src/test/java/org/semux/net/msg/p2p/WorldMessageTest.java
This pull request improves backward-compatibility of the P2P network protocol by allowing developers to add new message types without changing the number of `networkVersion`. There is now only a single mandatory capability `SEM`. In the future, we may like to introduce a few more capabilities such as batch synchronization and fast synchronization which can be implemented without breaking previous versions of Semux wallet.
=> Add Peer#capabilities

src/main/java/org/semux/gui/panel/ReceivePanel.java, src/main/resources/org/semux/gui/messages.properties
If the wallet file fails to save, do not let users add
accounts.  They could transfer funds to it, and they will
be lost forever!
fixes #514
=> GUI: Error message on failure to add account

src/main/java/org/semux/cli/SemuxCli.java, src/main/java/org/semux/gui/SemuxGui.java, src/main/java/org/semux/net/filter/SemuxIpFilter.java
related to #511
Main process could be stuck when there is an uncaught exception during kernel startup.
1. make the content of `config/ipfilter.json` become an invalid JSON
2. start `semux-cli.sh` or `semux-gui.sh`
=> Exit Process When There's an Uncaught Exception During Kernel Startup

config/log4j2.xml
When running a delegate, logging can become
large and unwieldy.  It is good to keep logs
manageable.
Also will allow users to post relevant log files
without posting 100's of MB of logs.
This will roll logs once per day.  We can also
add a max number of logs to retain.
=> Config: Use rolling file appender

src/test/java/org/semux/integration/ConnectionTest.java, src/test/java/org/semux/net/filter/SemuxIpFilterSaverTest.java
There are 2 known issues:
1. SemuxIpFilterSaverTest: `File#setWritable` doesn't work on Windows platform
2. ConnectionTest#testBlacklistIp: `127.0.0.1` is the only available loopback address on macOs platform
=> Fix ConnectionTest & SemuxIpFilterSaverTest

src/main/java/org/semux/Kernel.java, src/main/java/org/semux/Launcher.java, src/main/java/org/semux/cli/SemuxCli.java, src/main/resources/org/semux/cli/messages.properties, src/test/java/org/semux/TestLoggingAppender.java, src/test/java/org/semux/cli/SemuxCliTest.java
To resolve #532. The change ensures that log4j async loggers will be flushed in JVM shutdown hook by moving `Runtime#addShutdownHook` from Kernel class to Launcher class.
=> CLI: flush async loggers in Launcher class

.travis.yml
https://www.traviscistatus.com/incidents/1p7kw5hl4n1g
=> Tools: disable macOS CI build due to instability of travis-ci

src/main/java/org/semux/api/SemuxApiImpl.java
In some cases null was checked, in others null or empty.
Messages differed as well.  Bring this into alignment.
This should be more language agnostic.
=> API: Consistent error handling

src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/gui/dialog/InputDialog.java
Windows TaskBar lacks an entry or icon for the
InputDialog (Password entry)
Added java.awt.Dialog.ModalityType.TOOLKIT_MODAL
as an parameter to superConstructor
resolves #536
=> GUI: add InputDialog to Windows TaskBar

src/main/java/org/semux/api/ApiHandlerImpl.java, src/main/java/org/semux/api/Command.java, src/main/java/org/semux/api/SemuxApi.java, src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/api/response/SignMessageResponse.java, src/main/java/org/semux/api/response/VerifyMessageResponse.java, src/test/java/org/semux/api/ApiHandlerTest.java
Use the existing signatures to construct signed messages
This allows users to verify they control a given wallet
for trust
fixes #509
=> API: Add sign/verify messages calls

src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/gui/panel/ReceivePanel.java
Added Hex.PREF to the Address used by the QR creation method.
Currently the address for in the QR image is without  0x -prefix.
resolves #546
=> Util: Add prefix to address in generated QR Code

src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/gui/dialog/AddressBookDialog.java, src/main/resources/org/semux/gui/messages.properties
When adding a new entry to the address book, the handle cannot be
null or empty. Added a check and a Feedback Pane
resolves #573
=> GUI: added feedback for empty names on address book entries

src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/config/Config.java, src/main/java/org/semux/config/DevnetConfig.java, src/main/java/org/semux/config/MainnetConfig.java, src/main/java/org/semux/config/TestnetConfig.java, src/main/java/org/semux/net/Capability.java, src/main/java/org/semux/net/SemuxP2pHandler.java, src/test/java/org/semux/api/ApiHandlerTest.java, src/test/java/org/semux/net/PeerTest.java, src/test/java/org/semux/net/msg/p2p/HelloMessageTest.java, src/test/java/org/semux/net/msg/p2p/WorldMessageTest.java
As of v1.0.0 it is possible for a mainnet node to connect to a testnet node or the other way around.
A new mandatory capability `SEM_TESTNET` is created in place of `SEM` for testnet nodes.
=> Properly Separate Mainnet and Testnet

src/main/java/org/semux/consensus/SemuxSync.java
fix #585
As a validator, the local blockchain might be ahead of synchronization target that makes `SemuxSync` stuck forever.
=> Consensus: fix an issue that SemuxSync might be stuck forever as a validator

pom.xml
to avoid [CVE-2017-17485](https://nvd.nist.gov/vuln/detail/CVE-2017-17485)
=> Tools: upgrade Jackson to 2.9.4

src/main/java/org/semux/gui/SwingUtil.java
For delegates panel, we show 0 for < 1 sem
As we allow fractional SEM votes, we should show
to same precison as elsewhere.
Also only show precision to just number available.
So we will render 3 instead of 3.000 and 3.2 instead
of 3.200.  This can allow us to choose to render more
decimals if we want without cluttering UI if user only
uses full SEM.
this also helps where folks say they believe that other
validators with 'same' number of votes took their spot
when its likely just a fractional vote that pushed them over
=> GUI: Render to highest precision

src/main/java/org/semux/api/ApiHandlerImpl.java, src/main/java/org/semux/api/SemuxApi.java, src/main/java/org/semux/api/SemuxApiImpl.java, src/test/java/org/semux/api/ApiHandlerTest.java
=> API: add a parameter 'name' to /create_account

src/main/java/org/semux/core/TransactionExecutor.java, src/test/java/org/semux/core/TransactionExecutorTest.java
return `INSUFFICIENT_ERROR` in place of `INSUFFICIENT_LOCKED` when there is no enough available balance for paying tx fee
=> Core: improve error reporting of UNVOTE transaction

src/main/java/org/semux/consensus/SemuxSync.java
To resolve: #585 
As a validator, `SemuxSync#process` could trigger `SemuxSync#stop` in its first scheduled execution:
https://github.com/semuxproject/semux/blob/e08bf781df8181362083a97224b48c9c5fdac9b3/src/main/java/org/semux/consensus/SemuxSync.java#L295-L304
which can be prior to the call of `SemuxSync#isRunning.wait()` in some rare cases, making `SemuxSync#isRunning` wait forever:
https://github.com/semuxproject/semux/blob/e08bf781df8181362083a97224b48c9c5fdac9b3/src/main/java/org/semux/consensus/SemuxSync.java#L139-L154
The pull request adds a timeout of 1 second to the call of `SemuxSync#isRunning.wait()`.
This issue is discovered by FindBugs, see http://findbugs.sourceforge.net/bugDescriptions.html#UW_UNCOND_WAIT
=> Consensus: fix unconditional wait of SemuxSync#isRunning

src/main/java/org/semux/gui/panel/ReceivePanel.java
=> GUI: link size of ReceivePanel#btnRenameAddress with other btns

src/main/java/org/semux/gui/SwingUtil.java, src/main/java/org/semux/gui/panel/ReceivePanel.java
* Clean up how address label is computed in transaction description.
```
alias => delegate name => abbreviation
```
* Remove the alias when removing an account
=> GUI: clean up address label

src/main/java/org/semux/gui/dialog/AddressBookUpdateDialog.java
Trivial, but let's prevent errant use by limiting max
length on address aliases.  Set to arbitrary 256 chars.
At that point, the name is longer than just raw address, 
and of limited value.
fixes #659
=> GUI: Validate address alias length

config/semux.properties, src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/net/NodeManager.java
fix #624 
```
$ dig mainnet.semux.net @8.8.8.8
; <<>> DiG 9.9.5-9+deb8u12-Debian <<>> mainnet.semux.net @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54467
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;mainnet.semux.net.             IN      A
;; ANSWER SECTION:
mainnet.semux.net.      599     IN      A       23.102.239.10
mainnet.semux.net.      599     IN      A       35.198.39.94
mainnet.semux.net.      599     IN      A       35.201.187.136
mainnet.semux.net.      599     IN      A       35.226.132.132
mainnet.semux.net.      599     IN      A       51.143.156.145
;; Query time: 12 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon …
```
=> Config, Net: add mainnet.semux.net as an alternative dns seed

src/main/java/org/semux/api/SemuxApi.java
match case of other methods and fix typo
=> Trivial: fix typos in API docs

.travis.yml, README.md, pom.xml, src/main/java/org/semux/Launcher.java, src/main/java/org/semux/util/SystemUtil.java
To fix #649 
Ethereumj appears to have resolved the issue of `Could not create random access file` by upgrading leveldb to 1.18: https://github.com/ethereum/ethereumj/issues/344#issuecomment-185990688
This upgrade is backward-compatible with v1.0.0 databases and tested on Windows 7 32bit with JDK8.
[VC++ 2012 Redist package](https://www.microsoft.com/en-us/download/details.aspx?id=30679) must be installed in place of VC++ 2010 Redist package.
=> Upgrade Leveldb From 1.8 to 1.18

src/main/java/org/semux/net/SemuxP2pHandler.java
In current implementation the P2P server returns the first 256 connected nodes whenever it receives a GET_NODES message, that may lead to unbalanced load on nodes considering that Semux network relies on a fixed set of seeders.
=> Net: shuffle the list of nodes returned from GET_NODES message in order to balance the load on nodes

src/main/java/org/semux/cli/SemuxCli.java, src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/config/exception/ConfigException.java, src/main/java/org/semux/gui/SemuxGui.java
Careless users may open their wallets to the public with default API username & password. This commit enforces users to change API username & password from default values before an API server can be started.
=> Config: disallow default API username or password

src/main/java/org/semux/wrapper/Wrapper.java, src/test/java/org/semux/wrapper/WrapperTest.java
I just realized #641 wasn't properly fixed due to a missing `--add-opens` package
=> Wrapper: add '--add-opens=java.base/sun.net.dns=ALL-UNNAMED' to avoid reflection warning

src/main/java/org/semux/consensus/SemuxBft.java, src/main/java/org/semux/core/Block.java, src/main/java/org/semux/core/Transaction.java, src/main/java/org/semux/crypto/Key.java, src/test/java/org/semux/consensus/SemuxBftTest.java, src/test/java/org/semux/core/BlockTest.java, src/test/java/org/semux/core/TransactionTest.java
Currently, each validator has a background thread
that takes in pending transactions and validates them.
When a block proposal comes in, the validator verifies each
transaction again.  As most validators will have most of the
pending transactions that the forger will have, optimize to
save double calculation.
This is noticed to improve block validation time by ~90%
On testnet validator for 5k transactions from around 2.2
seconds down to 20ms.
I'm not sure if with 100 validators if pending transactions
propagate fully, so the actual results may be less.
=> Consensus: Improve voting speed

src/main/java/org/semux/gui/SwingUtil.java, src/test/java/org/semux/gui/SwingUtilTest.java
Today I was thinking about replacing `Unit` class with an enum and I think the `BigDecimal` is not as good as the dedicated class to represent a Semux Amount. That could be the next step. Once this one is merged, I will prepare new pull-request with `Unit` enum and dedicated class representing an amount.
=> GUI: use BigDecimal instead of double for correctness

src/main/java/org/semux/core/Wallet.java
#718 was mistakenly merged directly into `master` branch.
Maybe we should consider changing the default branch from `master` to `develop` to avoid this kind of mistake. See: https://help.github.com/articles/setting-the-default-branch/
=> Merge master into develop

src/main/java/org/semux/config/TestnetConfig.java, src/main/java/org/semux/core/PendingManager.java
For testing purposes and performance tuning
it is desirable to be able to test larger amounts
of transactions than would normally make sense
in order to identify bottlenecks for future growth 
and optimization.
Note: This will affect concensus during rollout, but as it is testnet
it seems fine if during rollout that larger blocks will
fail validation until we get 67%.  The backup validator will
propose the smaller block and not hang concensus.
If we decide to go with larger blocks in future, we'll
have to use @cryptokat 's method for signaling forks,
but this is just for test purposes, and not proposing larger
blocks overall at this time.
fixes #706 
Also trivial rename for clarity.
=> Concensus: Testnet permits larger blocks

src/main/java/org/semux/api/ConsoleApi.java, src/main/java/org/semux/api/ConsoleApiImpl.java, src/main/java/org/semux/gui/dialog/ConsoleDialog.java, src/test/java/org/semux/gui/dialog/ConsoleDialogTest.java
Add support for console API that isn't in REST
API.  As the console only supports string parameters
we add a getBlockByNumber.
This allows for additional console methods in the
future as well.
fixes #699
=> GUI: Add getBlockByNumber to console

findbugs-exclude.xml, pom.xml, src/main/java/org/semux/api/ConsoleApi.java, src/main/java/org/semux/api/ConsoleApiImpl.java, src/main/java/org/semux/api/SemuxApiImpl.java, src/main/java/org/semux/cli/SemuxCli.java, src/main/java/org/semux/gui/SwingUtil.java, src/main/java/org/semux/util/ConsoleUtil.java, src/main/java/org/semux/util/IOUtil.java, src/main/java/org/semux/util/SystemUtil.java, src/test/java/org/semux/bench/SemuxPerformance.java, src/test/java/org/semux/cli/SemuxCliTest.java, src/test/java/org/semux/gui/SwingUtilTest.java, src/test/java/org/semux/util/IOUtilTest.java
=> Util: Improve UTF8 CharSet Expression and Revert Scanner Default Charset

src/main/java/org/semux/consensus/SemuxBft.java, src/main/java/org/semux/consensus/Vote.java
Currently, an incoming vote is validated 3 times (first time in onMessage, second time in onVote, and finally it is validated again when it's added to the VoteSet). To avoid that, a memoization is applied to Vote#validate. Forcing validation is possible by calling the overloaded Vote#validate with revalidate parameter set to true.
=> Consensus: adding memoization to Vote#validate to avoid repeated validations

src/main/java/org/semux/api/http/HttpHandler.java, src/main/java/org/semux/net/NodeManager.java
update comments to match implementation.
And for QueryStringDecoder, remove workaround for empty sets.
If implementation changes to use say Collections.singleton,
the existing code would break anyway.  If we're going to modify
list always make sure it's editable
=> Trivial: comments and fix implementation specific code

src/main/java/org/semux/gui/SemuxGui.java, src/main/resources/org/semux/gui/messages.properties, src/test/java/org/semux/gui/SemuxGuiTest.java
Update the loop for checking versions to
1) check at first startup, then every 8 hours, instead
of once every 5 minutes
2) Add check against latest to inform user when a new
version has been posted, but only notify them once per
session.
fixes #754
=>  GUI: Notify user when there are updates 

src/main/java/org/semux/api/v2_0_0/TypeFactory.java, src/main/java/org/semux/api/v2_0_0/impl/SemuxApiServiceImpl.java, src/main/java/org/semux/core/Blockchain.java, src/main/java/org/semux/core/BlockchainImpl.java, src/test/java/org/semux/api/v2_0_0/SemuxApiTest.java
This makes it easier for API consumers to account for block rewards.
=> API: include COINBASE transaction in block response

src/main/java/org/semux/core/Wallet.java
Increment wallet version to add bcrypt hashing to generate
password for aes key.  This takes about 330ms on fairly
standard hardware.
fixes #758
=> Wallet: Update security of wallet with bcrypt

src/main/java/org/semux/consensus/SemuxBft.java, src/main/java/org/semux/consensus/SemuxSync.java, src/main/java/org/semux/core/BlockchainImpl.java, src/main/java/org/semux/core/PendingManager.java, src/main/java/org/semux/core/TransactionResult.java, src/test/java/org/semux/TestUtils.java, src/test/java/org/semux/consensus/SemuxBftTest.java, src/test/java/org/semux/consensus/SemuxSyncTest.java, src/test/java/org/semux/core/PendingManagerTest.java
=> Consensus: add restrictions on coinbase & recipient

src/test/java/org/semux/core/WalletTest.java
disable `testIsPosixPermissionSecured` on non-posix platforms
=> Tests: fix WalletTest#testIsPosixPermissionSecured

src/main/java/org/semux/api/Version.java, src/main/java/org/semux/api/http/HttpHandler.java, src/main/java/org/semux/api/http/SemuxApiService.java, src/main/java/org/semux/api/v1_0_1/ApiHandlerImpl.java, src/test/java/org/semux/api/http/HttpHandlerTest.java, src/test/java/org/semux/api/v2_0_0/SemuxApiErrorTest.java, src/test/java/org/semux/api/v2_0_0/SemuxApiTestBase.java
`Map<Version, ApiHandler> apiHandlers` should be initialized for only once.
Related: #704
=> Improper initialization of HttpHandler causing serious API performance degrade

.gitignore, config/log4j2.xml, src/main/java/org/semux/event/PubSub.java, src/main/java/org/semux/gui/SplashScreen.java, src/main/java/org/semux/log/LoggerConfigurator.java, src/main/java/org/semux/net/filter/SemuxIpFilter.java, src/test/java/org/semux/api/v1_0_1/ApiHandlerErrorTest.java, src/test/java/org/semux/integration/ConnectionTest.java, src/test/resources/log4j2-test.xml
The CI logs are too long to read. Time to clean up.
Still haven't figured out how to disable logs from `KernelRule`
=> Util: adjust test log levels

pom.xml
=> Tools: remove appbundle & change java download url to oracle's site

Dockerfile
```
semux_1  | 23:35:04.164 WARN     Native           Failed to load native library: /native/linux64/libsodium.so.23
semux_1  | java.lang.UnsatisfiedLinkError: /tmp/native8896693692344773996/libsodium.so.23: Error relocating /tmp/native8896693692344773996/libsodium.so.23: __memcpy_chk: symbol not found
semux_1  |      at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_151]
semux_1  |      at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_151]
semux_1  |      at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_151]
semux_1  |      at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_151]
semux_1  |      at java.lang.System.load(System.java:1086) ~[?:1.8.0_151]
semux_1  |      at org.semux.crypto.Native.loadLibrary(Native.java:85) …
```
=> Tools: change Docker base image to debian as native libs aren't supported on alpine

src/main/java/org/semux/api/v2_0_0/TypeFactory.java, src/main/java/org/semux/api/v2_0_0/impl/SemuxApiServiceImpl.java, src/main/resources/org/semux/api/v2_0_0/swagger.json
=> API: improve API descriptions

src/main/java/org/semux/api/v2_0_0/TypeFactory.java, src/main/resources/org/semux/api/v2_0_0/swagger.json, src/test/java/org/semux/api/v2_0_0/SemuxApiTest.java
~~~ISO-8601 is a broadly supported date format by multiple languages. For example, in Javascript a `Date` object can be directly constructed using an ISO-8601 string, while the original format of `YYYY-MM-DD` isn't supported.~~~
=> API: remove BlockType#date in favour of BlockType#timestamp

src/main/java/org/semux/gui/WelcomeFrame.java
Error of `Wallet already exists!` can be triggered by double-clicking `Next` button of welcome dialog during wallet encryption/decryption.
=> GUI: avoid 'Wallet already exists!' error triggered by double clicking 'Next' button of welcome frame

src/main/java/org/semux/cli/SemuxCli.java, src/test/java/org/semux/cli/SemuxCliTest.java
If user desires privateKey, they can use the dumpPrivateKey command
Avoid logging to file the private key.  I had considered moving to
System.out.println, but we cannot guarentee order, seems safer to allow
user to choose whether public key gets logged (they can just use the
dump command if they need it)
fixes #863
=> CLI: Don't dump private key on create

src/main/java/org/semux/core/Transaction.java
Although it's almost impossible to generate a private key mapping to
EMPTY_ADDRESS, it's still preferred to add this rule as the address is
being used as proof-of-burn on the Semux blockchain.
=> Core: prevent EMPTY_ADDRESS from sending transactions

src/main/java/org/semux/api/v2_0_0/impl/SemuxApiServiceImpl.java, src/main/java/org/semux/consensus/SemuxSync.java, src/main/java/org/semux/core/SyncManager.java, src/main/resources/org/semux/api/v2_0_0/swagger.json, src/test/java/org/semux/api/v2_0_0/SemuxApiTest.java, src/test/java/org/semux/gui/SemuxGuiTest.java
This API allows consumers to retrieve current sync status programmatically
=> API: add 'GET /syncing' endpoint

src/main/java/org/semux/gui/panel/DelegatesPanel.java, src/main/java/org/semux/gui/panel/SendPanel.java
If we update select boxes while user is interacting with it,
It re-renders the page and loses context/state of scrolling.
This is annoying for users.  If they are interacting with
the box, we have high confidence that data is not changing
elsewhere, or it can wait until next refresh.
=> GUI: Don't update dropdowns if user is interacting

src/main/java/org/semux/gui/ComboBoxItem.java, src/main/java/org/semux/gui/SwingUtil.java, src/main/java/org/semux/gui/panel/TransactionsPanel.java, src/main/java/org/semux/gui/panel/TransactionsPanelFilter.java
It's very difficult to locate a given transaction currently,
particularly for pool operators or heavy usage users.
Add filterable dropdowns to transactions panel.
fixes #550
=> GUI: Add transactions filtering

src/main/java/org/semux/api/ApiHandlerImpl.java, src/main/java/org/semux/api/v2_1_0/impl/SemuxApiServiceImpl.java, src/main/java/org/semux/core/PendingManager.java, src/main/resources/org/semux/api/v2_1_0/swagger.html, src/main/resources/org/semux/api/v2_1_0/swagger.json, src/test/java/org/semux/TestUtils.java, src/test/java/org/semux/api/v1_0_1/ApiHandlerTest.java, src/test/java/org/semux/api/v2_0_0/SemuxApiTest.java, src/test/java/org/semux/api/v2_1_0/SemuxApiTest.java
=> API: Add Optional 'nonce' and 'validateNonce' Parameters to Transaction Ops of API 2.1

src/main/java/org/semux/api/v2_1_0/impl/SemuxApiServiceImpl.java, src/main/java/org/semux/core/Wallet.java, src/main/resources/org/semux/api/v2_1_0/swagger.json, src/test/java/org/semux/api/v2_1_0/SemuxApiTest.java
=> API: Add Delete Account and Import Private Key Features

src/main/java/org/semux/net/msg/consensus/BlockHeaderMessage.java, src/main/java/org/semux/net/msg/consensus/GetBlockHeaderMessage.java, src/test/java/org/semux/net/msg/consensus/BlockHeaderMessageTest.java, src/test/java/org/semux/net/msg/consensus/GetBlockHeaderMessageTest.java
=> Net: fix block header message constructors

src/main/java/org/semux/gui/panel/TransactionsPanel.java
When window resizes, keep filters same vertical height.
fixes #896
=> GUI: Fix rendering of filters on resize

src/main/java/org/semux/gui/panel/SendPanel.java
Select account uses array ordering.
This fixes the 1.2.0 branch and should be considered and emergency fixpack
The RC will select the wrong account.
=> GUI: fix account ordering on select from account
